services:
    golang_backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_PORT: 3030
        ports:
            - 3030:3030
        command: go run main.go 
        volumes:
            - .:/app
